#' Branch computes a subdivision of a triangle
#'
#' @param interval A subinterval of [-pi, pi].
#' @param init Generates from SET a list with the following attributes
#' - size
#' - upper bound (ub)
#' - lower bound (lb)
#' @param mid A rule to compute the midpoint of the interval.
#'
#' @return A list of triangles generated by INIT.
#' @author Johannes Wieditz

branch.circle <- function (interval, init = INIT, mid = MID){

  c( init( list( list( left = interval$left, right = mid(interval) ) ,
                 list( left = mid(interval), right = interval$right)
               )
    )
  )
}

#' mid.circle computes the midpoint of an intervall
#'
#' @param interval An interval, i.e. a list with the attributes left and right.
#'
#' @result The midpoint of the interval.
#' @author Johannes Wieditz

mid.circle <- function( interval ){

  (interval$left + interval$right) / 2

}

#' The arc length metric on the circle.
#'
#' @param x The angle on a point on the unit circle.
#' @param y The angle on a point on the unit circle.
#'
#' @result The arc length distance between x and y.
#' @author Johannes Wieditz

darc.circle <- function (x, y) {

  d <- abs( x - y )
  ifelse( d <= pi, d, 2 * pi - d )

}

#' Formats the passed set into a data format which can be processed by the branch and bound algorithm.
#'
#' @param set A list of intervals.
#'
#' @result A list where every entry consists of the entries
#' * set description
#' * size as the length of the interval
#' * upper bound as function value at the midpoint
#' * lower bound using triangle inequality/ Lipschitz constant
#' @author Johannes Wieditz

init.3ineq.circle <- function( set, ... ) {

  L <- list()
  for( X in set ){
    f <- Fnhat( mid.circle(X), d = darc.circle() )
    L <- push(L, c(X, size = size.interval(X), ub = f , lb = max(0, f - 2 * pi * size.interval(X))) )
  }
  L
}

#' Compute the size of an interval.
#'
#' @param interval An interval (list with entries right and left).
#'
#' @result The length of the interval.
#' @author Johannes Wieditz

size.interval <- function( interval ){

  interval$right - interval$left

}

#' Formats the passed set into a data format which can be processed by the branch and bound algorithm.
#'
#' @param set A list of intervals.
#'
#' @result A list where every entry consists of the entries
#' * set description
#' * size as the length of the interval
#' * upper bound as function value at the midpoint
#' * lower bound using the geometrical construction
#' @references Eichfelder, Gabriele, Hotz, Thomas, Wieditz, Johannes (2018) - An algorithm for computing Fréchet means on the sphere.
#' @author Johannes Wieditz

init.acc.circle <- function( set, ... ) {

  L <- list()
  for( X in set ){
    lb <- 0
    for( i in 1:length(x)){

      if( !(X$left <= x[[i]] && X$right >= x[[i]]) ){

        lb <- lb + min( darc.circle(X$left, x[[i]])^p, darc.circle(X$right, x[[i]])^p )
      }
    }

    L <- push(L, c(X, size = size.interval(X), ub = Fnhat( mid.circle(X), d = darc.circle ) , lb = lb/length(x)) )
  }
  L
}

#' Computes the surface measure of a list of intervals.
#'
#' @param A A list of intervals.
#'
#' @result The total surface measure covered by the intervals contained in A.
#' @author Johannes Wieditz

size.circle <- function( A ) {

  size <- 0
  for ( X in A ){
    size <- size + X$size
  }
  size
}
